---
functional:
  - Зарегистрированные пользователи могут общаться в чате 
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Возможность смотреть ход игры авторизованными пользователями
  - Пользователь может выбрать игру по уровню сложности
  - Пользователь может при создании игры выбрать определенную игру
  - Пользователь может играть с любым человеком, с ботом или другом 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
    Google Chrome версия 96, 
    Mozilla Firefox версия 95  
    Safari версия 15 
    Microsoft Edge версия 96

Однако, рекомендуется проверить актуальные версии браузеров на момент проведения тестирования, так как они могли обновиться после этого времени.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Личные данные должны надежно храниться на серверах и должны быть защищены от взлома
  - Понятность интерфейса, т.е. игроки на разных языках программирования легко понимают и взаимодействуют с игрой
