---
functional:
  - Зарегистрированные пользователи могут общаться в чате 
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Другие пользователи могут следить за ходом игры
  - Пользователь может выбрать игру по уровню сложности
  - Пользователь может при создании игры выбрать определенную игру
  - Пользователь может играть с любым человеком, с ботом или другом 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Личные данные должны надежно храниться на серверах и должны быть защищены от взлома
  - Понятность интерфейса, т.е. игроки на разных языках программирования легко понимают и взаимодействуют с игрой
